"""Type stubs for the native module.

Not the package's public interface — see ``pixelmap_multiview/__init__.py`` for that.
These exist so that type checkers can follow the wrapper's calls into Rust.
"""

from typing import Any, Callable

import numpy as np
from numpy.typing import NDArray

MIN_VIEWS: int
MIN_DIMENSION: int
MIN_PAIR_COVERAGE: float
DEFAULT_MAX_TEXTURE_SIZE: int
STAGES: list[tuple[str, str]]

class Model:
    @property
    def vertices(self) -> NDArray[np.float64]: ...
    @property
    def normals(self) -> NDArray[np.float64]: ...
    @property
    def triangles(self) -> NDArray[np.uint32]: ...
    @property
    def vertex_colours(self) -> NDArray[np.uint8]: ...
    @property
    def atlas(self) -> NDArray[np.uint8]: ...
    @property
    def texcoords(self) -> NDArray[np.float32]: ...
    @property
    def face_texcoords(self) -> NDArray[np.uint32]: ...
    @property
    def face_views(self) -> NDArray[np.uint32]: ...
    @property
    def charts(self) -> int: ...
    @property
    def atlas_scale(self) -> float: ...
    @property
    def intrinsics(self) -> dict[str, Any]: ...
    @property
    def cameras(self) -> list[dict[str, NDArray[np.float64]] | None]: ...
    @property
    def views(self) -> int: ...
    @property
    def connected(self) -> list[int]: ...
    @property
    def pairs(self) -> list[dict[str, Any]]: ...
    def obj(self, material_library: str) -> bytes: ...
    def mtl(self, texture_file: str) -> bytes: ...
    def ply(self) -> bytes: ...
    def x3d(self, texture_file: str) -> bytes: ...
    def glb(self) -> bytes: ...
    def html(self, title: str) -> bytes: ...
    def atlas_png(self) -> bytes: ...

class Job:
    def next_event(
        self, timeout: float | None = None
    ) -> tuple[str, dict[str, Any]] | None: ...
    def status(self) -> dict[str, Any]: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...
    def join(self) -> Model: ...

def run(
    photos: list[NDArray[np.uint8]],
    quality: str,
    focal_kind: str,
    focal_value: float,
    seed: int | None,
    refine_focal: bool,
    max_texture_size: int,
    on_event: Callable[[str, dict[str, Any]], None] | None,
) -> Model: ...
def start(
    photos: list[NDArray[np.uint8]],
    quality: str,
    focal_kind: str,
    focal_value: float,
    seed: int | None,
    refine_focal: bool,
    max_texture_size: int,
) -> Job: ...
def _synthetic_orbit(
    scene: str, views: int, spread_deg: float, width: int, height: int
) -> list[NDArray[np.uint8]]: ...
